// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ApiTestClient is the client API for ApiTest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiTestClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type apiTestClient struct {
	cc grpc.ClientConnInterface
}

func NewApiTestClient(cc grpc.ClientConnInterface) ApiTestClient {
	return &apiTestClient{cc}
}

func (c *apiTestClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/todo.serv.ApiTest/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiTestServer is the server API for ApiTest service.
// All implementations must embed UnimplementedApiTestServer
// for forward compatibility
type ApiTestServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedApiTestServer()
}

// UnimplementedApiTestServer must be embedded to have forward compatible implementations.
type UnimplementedApiTestServer struct {
}

func (UnimplementedApiTestServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedApiTestServer) mustEmbedUnimplementedApiTestServer() {}

// UnsafeApiTestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiTestServer will
// result in compilation errors.
type UnsafeApiTestServer interface {
	mustEmbedUnimplementedApiTestServer()
}

func RegisterApiTestServer(s grpc.ServiceRegistrar, srv ApiTestServer) {
	s.RegisterService(&ApiTest_ServiceDesc, srv)
}

func _ApiTest_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiTestServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.serv.ApiTest/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiTestServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiTest_ServiceDesc is the grpc.ServiceDesc for ApiTest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiTest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "todo.serv.ApiTest",
	HandlerType: (*ApiTestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _ApiTest_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ApiTest.proto",
}
