// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// F2DddClient is the client API for F2Ddd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type F2DddClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type f2DddClient struct {
	cc grpc.ClientConnInterface
}

func NewF2DddClient(cc grpc.ClientConnInterface) F2DddClient {
	return &f2DddClient{cc}
}

func (c *f2DddClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/ddd.ffff.F2ddd/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// F2DddServer is the server API for F2Ddd service.
// All implementations must embed UnimplementedF2DddServer
// for forward compatibility
type F2DddServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedF2DddServer()
}

// UnimplementedF2DddServer must be embedded to have forward compatible implementations.
type UnimplementedF2DddServer struct {
}

func (UnimplementedF2DddServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedF2DddServer) mustEmbedUnimplementedF2DddServer() {}

// UnsafeF2DddServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to F2DddServer will
// result in compilation errors.
type UnsafeF2DddServer interface {
	mustEmbedUnimplementedF2DddServer()
}

func RegisterF2DddServer(s grpc.ServiceRegistrar, srv F2DddServer) {
	s.RegisterService(&F2Ddd_ServiceDesc, srv)
}

func _F2Ddd_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(F2DddServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ddd.ffff.F2ddd/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(F2DddServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// F2Ddd_ServiceDesc is the grpc.ServiceDesc for F2Ddd service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var F2Ddd_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ddd.ffff.F2ddd",
	HandlerType: (*F2DddServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _F2Ddd_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "F2ddd.proto",
}
