// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BaaaClient is the client API for Baaa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaaaClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type baaaClient struct {
	cc grpc.ClientConnInterface
}

func NewBaaaClient(cc grpc.ClientConnInterface) BaaaClient {
	return &baaaClient{cc}
}

func (c *baaaClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sport.aaa.Baaa/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaaaServer is the server API for Baaa service.
// All implementations must embed UnimplementedBaaaServer
// for forward compatibility
type BaaaServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedBaaaServer()
}

// UnimplementedBaaaServer must be embedded to have forward compatible implementations.
type UnimplementedBaaaServer struct {
}

func (UnimplementedBaaaServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedBaaaServer) mustEmbedUnimplementedBaaaServer() {}

// UnsafeBaaaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaaaServer will
// result in compilation errors.
type UnsafeBaaaServer interface {
	mustEmbedUnimplementedBaaaServer()
}

func RegisterBaaaServer(s grpc.ServiceRegistrar, srv BaaaServer) {
	s.RegisterService(&Baaa_ServiceDesc, srv)
}

func _Baaa_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaaaServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sport.aaa.Baaa/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaaaServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Baaa_ServiceDesc is the grpc.ServiceDesc for Baaa service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Baaa_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sport.aaa.Baaa",
	HandlerType: (*BaaaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Baaa_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Baaa.proto",
}
